name: 'Monorepo Release'

description: 'Releases individual packages of a monorepo once they are pushed to their split repositories'

inputs:
  publish_npm_package:
    description: 'Wether or not a NPM package should be published'
    type: boolean
    required: false
    default: false
  github-token:
    required: true
  npm-token:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0

    - name: Check Version Change
      uses: EndBug/version-check@v2.1.1
      id: version
      with:
        diff-search: true

    - name: Version Update Detected
      if: ${{ steps.version.outputs.changed == 'true' }}
      shell: bash
      run: 'echo "Version change found! New version: ${{ steps.version.outputs.version }} (${{ steps.version.outputs.type }})"'

    - name: Install Dependencies
      if: ${{ steps.version.outputs.changed == 'true' }}
      shell: bash
      run: npm install

    - name: Tag
      if: ${{ steps.version.outputs.changed == 'true' }}
      uses: fundamend/action-github-tag@main
      with:
        tag: ${{ steps.version.outputs.version }}
        github-token: ${{ inputs.bithub-token }}

    - name: Checkout
      if: ${{ steps.version.outputs.changed == 'true' }}
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0

    - name: Create GitHub Release
      if: ${{ steps.version.outputs.changed == 'true' }}
      shell: bash
      env:
        CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ inputs.github-token }}
      run: 'npx conventional-github-releaser --preset conventionalcommits'

    - name: 'Configure NPM'
      if: ${{ steps.version.outputs.changed == 'true' && inputs.publish_npm_package == 'true' }}
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken="${{ inputs.npm-token }}"" > .npmrc

    - name: Publish to NPM
      if: ${{ steps.version.outputs.changed == 'true' && inputs.publish_npm_package == 'true' }}
      shell: bash
      run: npm publish

branding:
  icon: box
  color: purple
